#!/usr/bin/env python

from scheduler.models import Worker, Student, HighSchool, MiddleSchool
import csv
import StringIO


def parse_students(doc):
    doc = '\n'.join(doc.splitlines())
    f = StringIO.StringIO(doc)
    reader = csv.DictReader(f, delimiter=',')
    students = []
    hs, ms = HighSchool(), MiddleSchool()
    schools = [ms for i in range(8)] + [hs for i in range(4)]
    for row in reader:
        try:
            students.append(Student.from_row(schools, row))
        except Exception:
            print 'error on line {}'.format(reader.line_num)
            raise
    return students

if __name__ == "__main__":

    with open('/Users/jmiller/Desktop/students.csv', 'r') as f:
        students = parse_students(f.read())
    worker = Worker()
    map(worker.sched_student, students)
    worker.dump()
