#!/usr/bin/env python

from scheduler.models import Worker, Student, HighSchool, MiddleSchool
import csv
import StringIO
import argparse


def parse_students(doc):
    doc = '\n'.join(doc.splitlines())
    f = StringIO.StringIO(doc)
    reader = csv.DictReader(f, delimiter=',')
    students = []
    hs, ms = HighSchool(), MiddleSchool()
    schools = [ms for i in range(9)] + [hs for i in range(4)]
    for row in reader:
        try:
            students.append(Student.from_row(schools, row))
        except Exception:
            print 'error on line {}'.format(reader.line_num)
            raise
    return students

if __name__ == "__main__":

    parser = argparse.ArgumentParser()
    parser.add_argument("--file", type=str, action="store",
                        default='students.csv', help="path to csv")
    args = parser.parse_args()

    with open(args.file, 'r') as f:
        students = parse_students(f.read())
    worker = Worker()
    worker.schedule(students)
